### ISSUE TITLE
Problems with updates

### ISSUE THREAD

**Issue by jeremycherfas** [OleVik/grav-plugin-twigfeeds#13]
Sorry about this, but I am still having trouble getting the plugin to display the most up to date items. I have cache enabled and static cache disabled, and I still do not get updates unless I clear the caches.

What do you need from me to help troubleshoot?

**Comment by OleVik** [comment]
A snapshot of the RSS-data, your /user/config/plugins/twigfeeds.yaml, and your system.yaml, to see why there would be a mismatch between them and updates not coming through. If available, zipping up a copy of your /user-directory and sending it to me on Slack would allow me to more exactly replicate the issue.

Also, is your installation of Grav up to date? And what, if any, caching is present on the server? Does Apache have expires-headers set?

**Comment by jeremycherfas** [comment]
OK, here are the three smaller files, and I will send the whole user directory zipped to Slack.

[system.yaml.txt](https://github.com/OleVik/grav-plugin-twigfeeds/files/996020/system.yaml.txt)
[rss-raw-data.txt](https://github.com/OleVik/grav-plugin-twigfeeds/files/996023/rss-raw-data.txt)
[twigfeeds.yaml.txt](https://github.com/OleVik/grav-plugin-twigfeeds/files/996030/twigfeeds.yaml.txt)

Grav installation is fully up to date.

**Comment by OleVik** [comment]
Ok, I've dug into the issue, and there was an inherent problem in the logic of checking for updates. Namely, the manifest was updated prior to checking, and thus would continuously push the update-date forwards by the time set in `cache_time` - never actually downloading the newest data.

The resolution is fairly straightforward, and should work without requiring any clearing of the cache on your end once you install [v3.1.2](https://github.com/OleVik/grav-plugin-twigfeeds/releases/tag/v3.1.2).

Now, on updating the plugin _should not_ forcibly clear its own cache, because this is a patch-version change. I would greatly appreciate it if you verified whether the plugin's cache - in /cache/twigfeeds for your installation - is intact or not immediately after updating the plugin.

This was implemented in v3.1.1 to ensure cache-busting on major- or minor-version changes, which are API-breaking, as an emulation of Grav's `onBeforeCacheClear`-event.

**Comment by OleVik** [comment]
3.1.2 introduces a new issue, I removed the release temporarily to prevent erroneous updates.

**Comment by OleVik** [comment]
This should be fixed in [v3.2.0](https://github.com/OleVik/grav-plugin-twigfeeds/releases/tag/v3.2.0), which relocates the logic of recreating the manifest to only coincide with cache-busting. As it is a minor-version change, the cache should bust automatically on update.
