### ISSUE TITLE
Failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by paulhibbitts** [OleVik/grav-plugin-twigfeeds#25]
Hi Ole,

I've gotten this error message recently, but when I refresh the site everything displays a-ok:

![2019-01-14_07-38-22](https://user-images.githubusercontent.com/1812771/51122902-c8709000-17cf-11e9-924a-a7b3bea125e2.png)

![2019-01-14_07-38-27](https://user-images.githubusercontent.com/1812771/51122911-cc9cad80-17cf-11e9-8f31-8ee1fa6ef15d.png)

Please let me know if this looks like something on my end, or if I can test anything for you etc.

Thanks very much,
Paul

**Comment by paulhibbitts** [comment]
Another recent error message, which when the page reloaded went away... hopefully a clue!

![2019-01-15_13-19-15](https://user-images.githubusercontent.com/1812771/51210696-4a43e480-18c8-11e9-9468-482ea19cd12a.png)

**Comment by OleVik** [comment]
For the first problem, the best I can do is return an empty Twig-variable so the error is not thrown, but the list of feed items show up empty. It should then be filled upon reload. The point at which the error occurs indicates that the data was not already cached, which the plugin should have done just prior. You might try `debug: true` in the config to see if /logs/grav.log reveals any clues - the plugin is quite talkative in that mode.

The `readManifest()` error is hard to source, because manifests were always written as JSON to the filesystem. One hiccup was the comparison of existing and outdated files, though, were manifests and files were reloaded even if they weren't out of date. I fixed a few things in [v3.3.4](https://github.com/OleVik/grav-plugin-twigfeeds/releases/tag/v3.3.4) which should make such errors less common.

**Comment by paulhibbitts** [comment]
Thanks very much Ole, I will update my sites and loop back if I see the error happen again.
